import type { Metadata } from "next";
import { Geist, Geist_Mono, Noto_Serif, Mukta , Noto_Sans_Mono} from "next/font/google";
import { cookies } from "next/headers";
import "./globals.css";
import Head from "next/head";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const notoSerif = Noto_Serif({
  variable: "--font-noto-serif",
  subsets: ["latin"],
});
const mukta = Mukta({
  variable: "--font-noto-serif",
  subsets: ["latin"],
  weight:"500"
});
export const noto_sans = Noto_Sans_Mono({
  variable: "--font-mukta",
  subsets: ["latin"],
  weight:"500"
});

export const metadata: Metadata = {
  title: "Mug editor",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body
        className={` ${mukta.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
